PROVINCIAS = [
    (1, "Álava",  "01", "País Vasco"),
    (2, "Albacete", "02", "Castilla-La Mancha"),
    (3, "Alicante", "03", "Comunidad Valenciana"),
    (4, "Almería", "04", "Andalucía"),
    (5, "Ávila", "05", "Castilla y León"),
    (6, "Badajoz", "06", "Extremadura"),
    (7, "Illes Balears", "07", "Islas Baleares"),
    (8, "Barcelona", "08", "Cataluña"),
    (9, "Burgos", "09", "Castilla y León"),
    (10, "Cáceres", "10", "Extremadura"),
    (11, "Cádiz", "11", "Andalucía"),
    (12, "Castellón", "12", "Comunidad Valenciana"),
    (13, "Ciudad Real", "13", "Castilla-La Mancha"),
    (14, "Córdoba", "14", "Andalucía"),
    (15, "A Coruña", "15", "Galicia"),
    (16, "Cuenca", "16", "Castilla-La Mancha"),
    (17, "Girona", "17", "Cataluña"),
    (18, "Granada", "18", "Andalucía"),
    (19, "Guadalajara", "19", "Castilla-La Mancha"),
    (20, "Gipuzkoa", "20", "País Vasco"),
    (21, "Huelva", "21", "Andalucía"),
    (22, "Huesca", "22", "Aragón"),
    (23, "Jaén", "23", "Andalucía"),
    (24, "León", "24", "Castilla y León"),
    (25, "Lleida", "25", "Cataluña"),
    (26, "La Rioja", "26", "La Rioja"),
    (27, "Lugo", "27", "Galicia"),
    (28, "Madrid", "28", "Comunidad de Madrid"),
    (29, "Málaga", "29", "Andalucía"),
    (30, "Murcia", "30", "Región de Murcia"),
    (31, "Navarra", "31", "Comunidad Foral de Navarra"),
    (32, "Ourense", "32", "Galicia"),
    (33, "Asturias", "33", "Principado de Asturias"),
    (34, "Palencia", "34", "Castilla y León"),
    (35, "Las Palmas", "35", "Canarias"),
    (36, "Pontevedra", "36", "Galicia"),
    (37, "Salamanca", "37", "Castilla y León"),
    (38, "Santa Cruz de Tenerife", "38", "Canarias"),
    (39, "Cantabria", "39", "Cantabria"),
    (40, "Segovia", "40", "Castilla y León"),
    (41, "Sevilla", "41", "Andalucía"),
    (42, "Soria", "42", "Castilla y León"),
    (43, "Tarragona", "43", "Cataluña"),
    (44, "Teruel", "44", "Aragón"),
    (45, "Toledo", "45", "Castilla-La Mancha"),
    (46, "Valencia", "46", "Comunidad Valenciana"),
    (47, "Valladolid", "47", "Castilla y León"),
    (48, "Bizkaia", "48", "País Vasco"),
    (49, "Zamora", "49", "Castilla y León"),
    (50, "Zaragoza", "50", "Aragón"),
    (51, "Ceuta", "51", "Ceuta"),
    (52, "Melilla", "52", "Melilla"),
]

COMUNIDADES = [
    "Andalucía", "Aragón", "Asturias", "Islas Baleares", "Canarias",
    "Cantabria", "Castilla-La Mancha", "Castilla y León", "Cataluña",
    "Comunidad Valenciana", "Extremadura", "Galicia", "La Rioja",
    "Comunidad de Madrid", "Región de Murcia", "Navarra", "País Vasco",
    "Ceuta", "Melilla",
]
